### ISSUE TITLE
[linux] Can't install olympus on heroic games' version of celeste (uses proton/wine).

### ISSUE THREAD

**Issue by reDpz** [EverestAPI/Olympus#61]
It detects the install location but after installing everest the game will not launch and just will crash immediately

**Comment by Wartori54** [comment]
The heroic version of celeste is windows specific and cant be directly modded since the monomod will detect that its on linux and patch it for linux. That makes it break when it runs on wine.
Luckily for you there's a tool i made to convert heroic (or any windows) installs to linux: https://github.com/Wartori54/CelesteLinuxifier.
Follow the instructions there, and proceed to always launch the game from olympus and not touch it on heroic anymore. ;)
